"""Initial

Revision ID: 760db658c4ab
Revises: 
Create Date: 2021-11-21 16:20:30.267840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760db658c4ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=45), nullable=False),
    sa.Column('surname', sa.String(length=45), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('best_grade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('surname', sa.String(length=45), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=1000), nullable=True),
    sa.Column('accessusers', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=45), nullable=False),
    sa.Column('Student_id', sa.Integer(), nullable=True),
    sa.Column('user_creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Student_id'], ['Student.id'], ),
    sa.ForeignKeyConstraint(['user_creator_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Propeties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rating_id'], ['Rating.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Propeties')
    op.drop_table('Rating')
    op.drop_table('User')
    op.drop_table('Student')
    # ### end Alembic commands ###
